name: carousel_image_editor
description: "Carousel Image Editor Plugin with filters, drawing, text and emoji like stories."
version: 0.0.3
homepage: https://github.com/didiabel/carousel_image_editor
repository: https://github.com/didiabel/carousel_image_editor
platforms:
  android:
  ios:

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  colorfilter_generator: ^0.0.8
  extended_image: ^8.2.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_image_compress: ^2.2.0
  hand_signature: ^3.0.2
  image: ^4.1.7
  permission_handler: ^11.3.0
  reorderables: ^0.6.0
  screenshot: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
